os: linux
dist: bionic
language: csharp
dotnet: 3.1.404

install:
  - dotnet restore src/DbCtl.Sqlite.sln

script:
  - dotnet test src/DbCtl.Sqlite.Tests/DbCtl.Sqlite.Tests.csproj
  - dotnet build -c Release src/DbCtl.Sqlite.sln

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - dotnet publish -c Release src/DbCtl.Sqlite/DbCtl.Sqlite.csproj -p:PublishProfile=FolderProfile
  - zip -r DbCtl.Sqlite-$TRAVIS_TAG.zip src/DbCtl.Sqlite/bin/Release/netstandard2.1/publish/
  
deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: DbCtl.Sqlite-$TRAVIS_TAG.zip
  cleanup: true
  on:
    branch: main